version: '3.3'
# Usage for caveservice

#  -- After update just run deploy again
#   docker stack deploy --with-registry-auth -c cs-swarm.yml csstack

# docker service ls

# services will be deployed on nodes with node.labels.type = services
# databases will be deployed on nodes with node.labels.type = database

services:
  caveservice:
    image: b33rsledge/caveservice:v2
    environment:
      spring.redis.host: rediscs
      spring.redis.port: 6380
      spring.redis.timeout: 60000
      debug: "false"
      storage.room: redisStorage
    ports:
      - "8080:8080"
    networks:
      - cs-network
    depends_on:  #not working in swarm mode
      - rediscs
    command: java -jar /root/caveservice/caveservice.jar
    deploy:
      placement:
        constraints:
          - node.labels.type == services
      replicas: 1
      restart_policy:
        delay: 5s
        max_attempts: 5
    healthcheck:
      test: curl --fail -s http://localhost:8080/actuator/health || exit 1
      interval: 30s
      timeout: 15s
      retries: 3
  rediscs:
    image: redis:6.2.5-alpine
    command: --port 6380
    volumes:
      - redisdata_cs:/data/cs
    networks:
      - cs-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
      placement:
        constraints:
          - node.labels.type == database
#    healthcheck:
#      test: ["CMD", "redis-cli", "ping"]
#      interval: 60s
#     timeout: 3s
#      retries: 5
  messageservice:
    image: christianmaintz/sky-cave-message-service:latest
    environment:
      spring.profiles.active: redis
      redis.host: redisms
      redis.port: 6381
      spring.redis.timeout: 60000
      debug: "false"
    ports:
      - "5777:5777"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.type == services
    networks:
      - cs-network
    depends_on:  #not working in swarm mode
      - redisms
    command: "java -jar  /root/message/sky-cave-message-service-1.1.0.jar"
  redisms:
    image: redis:6.2.5-alpine
    command: --port 6381
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
      placement:
        constraints:
          - node.labels.type == database
    ports:
      - "6381"
    volumes:
      - redisdata_ms:/data/ms
    networks:
      - cs-network
  visualizer:
    image: dockersamples/visualizer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "9000:8080"
    networks:
      - cs-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
volumes:
  redisdata_cs:
    external: false
  redisdata_ms:
    external: false
networks:
  cs-network: {}
  public:
